version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://ztbzBackend:example@mongo:27017/ztbzDatabase

  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminRoot
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ztbzDatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


volumes:
  mongo_data:
