version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - postgres
      - influx
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://ztbzBackend:example@mongo:27017/ztbzDatabase

  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminRoot
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ztbzDatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=adminRoot
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=default_database
      - PGDATA=/data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  influx:
    image: influxdb:latest
    container_name: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/varlib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=adminRoot
      - DOCKER_INFLUXDB_INIT_PASSWORD=exampleexample
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ztbz-super-secret-auth-token
      - DOCKER_INFLUXDB_INIT_ORG=ztbzDatabase
      - DOCKER_INFLUXDB_INIT_BUCKET=ztbzTable

volumes:
  mongo_data:
  postgres:
    driver: local
  influxdb-storage:
